version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/ezops-test-mateuswelter
hooks:
  ApplicationStart:
    - location: docker-start.sh
      timeout: 300
      runas: root
